apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.19.1
    helm:
      releaseName: external-dns
      values: |-
        provider: aws
        policy: upsert-only
        sources:
          - ingress
        domainFilters:
          - devops-sandbox.aws.tsh.io	
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::005699609604:role/external-dnsIRSA-eks-demo-tsh
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
