---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo-workflows
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    chart: argo/argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision:
    helm:
      releaseName: argo-workflows
      values: |-
        server:
          extraArgs:
            - --auth-mode=server
  destination:
    name: in-cluster
    namespace: argo-workflows
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
