apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    chart: karpenter
    repoURL: public.ecr.aws/karpenter
    targetRevision: v0.27.3
    helm:
      releaseName: karpenter
      values: |-
        clusterName: "eks-demo-tsh"
        awsRegion: "eu-west-1"
        awsVpcId: "vpc-04b45e3f202617e19"
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::005699609604:role/eks-demo-tsh-KarpenterIRSA
  destination:
    name: in-cluster
    namespace: karpenter
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
